name: internalization_demo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/src/localization
  output_dir: lib/src/generated
  use_deferred_loading: false
  # here for the optional localizely settings