name: gorouter_part
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_strategy: ^0.2.0
  collection: ^1.18.0
  go_router: ^14.1.0
  go_transitions: ^0.5.2
  logging: ^1.2.0
  logging_appenders: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
